### PR TITLE
TomlArray support for IsMultiline

### PR DESCRIPTION
**Pull request by gibbed**
This is a quick & dirty implementation, but it seems OK.

https://toml.io/en/v1.0.0#array

```toml
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
```

### CODE REVIEW

**Comment by dezhidki** [comment]
Hi!

Thanks for the PR and sorry for quite the delay on the response!

From the looks of it, it appears like you're essentially reimplementing [`TomlArray.ToString`](https://github.com/dezhidki/Tommy/blob/b3789163b6d8a604e22e7c9747244a1a7bead353/Tommy/Tommy.cs#L347-L359) with the only difference of it including newlines. I'd rather not have duplicate functionality.

How about instead doing something like the following?

* Move code of `TomlArray.ToString()` to its own separate `TomlArray.ToString(bool multiline)` overload
* Have `TomlArray.ToString()` call `TomlArray.ToString(false)`
* Have `TomlArray.WriteTo` call `TomlArray.ToString(IsMultiline)` instead of `ToInlineToml()` (I initially made it call that instead of `ToString` because it makes for a bit more readable code; if you look at the default `ToInlineToml()` implementation, it just calls `ToString()`)
* Finally modify `TomlArray.ToString(bool multiline)` so that
    * When `multiline = false`, it uses `" "` as  starting/ending whitespace and `$"{TomlSyntax.ITEM_SEPARATOR} "` as item separator (i.e. current behaviour)
    * When `multiline = false`, it uses `Environment.NewLine` as starting/ending whitespace and `$"{TomlSyntax.ITEM_SEPARATOR}{Environment.NewLine}"` as item separator. You might also add some prefixing spacing if you want. Either way, I'd probably reuse the `string.Join` to keep overall code short

**Comment by gibbed** [comment]
That's fair, I'll make those changes and update the PR when I have a moment.

**Comment by gibbed** [comment]
The PR has been updated.

I ended up making the chained appends an if branch because it seemed a bit messy to do `?:` inside the `Append`s. Let me know if that's what you would prefer anyway.

**Comment by dezhidki** [comment]
Nice, this looks good to me!

One small thing before I'll PR this: I think that instead of two separate Joins you could put the separator strings into variables as follows:

```cs
var arrayStart = multiline ? $"{Environment.NewLine}  " : " ";
var arraySeparator = multiline ? $"{TomlSyntax.ITEM_SEPARATOR}{Environment.NewLine}  " : $"{TomlSyntax.ITEM_SEPARATOR} ";
var arrayEnd = multiline ? Environment.NewLine : " ";
```

and then have just one Append/Join with these variables:

```cs
sb.Append(arrayStart)
    .Append(arraySeparator.Join(RawArray.Select(n => n.ToInlineToml())))
    .Append(arrayEnd);
```

This should end up a bit more legible (no need for duplicate array construction). I personally don't mine the use of `?:` in this way since it ends up being more readable in the end.

Do tell how you end up proceeding. I'm fine with merging this as-is, although I'll likely do the above change myself should you decide not to.

**Comment by gibbed** [comment]
I had considered that, if that's what you'd prefer then that would work too!

I'll make the change.

**Comment by gibbed** [comment]
PR has been updated.

**Comment by dezhidki** [comment]
Looks good to me now!

Thank you again for the PR. I'll merge it now but won't likely release a new version right away since there are some issues to look at. I'll try to handle them as soon as possible.

**Comment by gibbed** [comment]
No problem! I'm using my own fork at this point, bouncing from this PR and back, with all those extra forced commits is me fixing issues from duplicating changes.

**Pull request merged**
